# Generated by Django 6.0.1 on 2026-02-10 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('hash_keccak256', models.CharField(db_index=True, max_length=64)),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('tamano_bytes', models.BigIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_hashes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hash de Archivo',
                'verbose_name_plural': 'Hashes de Archivos',
                'ordering': ['-fecha_procesamiento'],
                'indexes': [models.Index(fields=['-fecha_procesamiento'], name='file_hasher_fecha_p_d47be5_idx'), models.Index(fields=['usuario', '-fecha_procesamiento'], name='file_hasher_usuario_717002_idx')],
            },
        ),
    ]
